<h3><?=t('Add user to Group: <em>@group</em>', array('@group' => $group->__toString())); ?> </h3>

<form method="post" action="" class="message_edit">
  <?php if (isset($_SERVER['HTTP_REFERER'])): ?>
    <input name="dest" type="hidden" value="<?=$_SERVER['HTTP_REFERER']?>"/>
  <?php endif; ?>
  <fieldset>
    <div class="fieldset-wrapper">

      <div class="form-item form-type-textfield">
        <label><?=t("User to add")?>:</label>
        <select name="user">
          <?php foreach(user_active_record::search()->where('status',1)->order('name','asc')->exec() as $user): ?>
            <option value="<?=$user->uid?>"><?=$user->name?></option>
          <?php endforeach; ?>
        </select>
      </div>

    </div>
  </fieldset>
  <div class="form-actions" id="edit-actions">
    <input type="submit" id="edit-submit" name="op" value="<?=t("Add user")?>" class="form-submit">
  </div>
</form>
